### PR TITLE
Interpret Postgres connect errors to user-facing

### LINKED ISSUE #93: Status 500
Hi,
when running the UI with this command: `docker run -p 8080:8080 --env DATABASE_URL="host=localhost user=postgres 
password=postgres dbname=main port=5433 sslmode=disable" ghcr.io/riverqueue/riverui:latest` to a database with fully initialized river tables, I get `unhandled response with status 500` in the UI. Here's the logs:
```bash
No .env file detected, using environment variables
2024/07/11 18:37:58 starting server on :8080
time=2024-07-11T18:38:09.116Z level=INFO msg="200: OK" request.time=2024-07-11T18:38:09.116Z request.method=GET request.host=localhost:8080 request.path=/jobs request.query="state=running" request.ip=172.17.0.1:47874 request.referer="" request.length=0 response.time=2024-07-11T18:38:09.116Z response.latency=63.61µs response.status=200 response.length=972
time=2024-07-11T18:38:09.216Z level=INFO msg="200: OK" request.time=2024-07-11T18:38:09.216Z request.method=GET request.host=localhost:8080 request.path=/assets/dagrejs-BYkk81-A.js request.query="" request.ip=172.17.0.1:47878 request.referer="http://localhost:8080/jobs?state=running" request.length=0 response.time=2024-07-11T18:38:09.216Z response.latency=305.549µs response.status=200 response.length=39802
time=2024-07-11T18:38:09.217Z level=INFO msg="200: OK" request.time=2024-07-11T18:38:09.215Z request.method=GET request.host=localhost:8080 request.path=/assets/index-RFQUt6mt.js request.query="" request.ip=172.17.0.1:47874 request.referer="http://localhost:8080/jobs?state=running" request.length=0 response.time=2024-07-11T18:38:09.217Z response.latency=1.300334ms response.status=200 response.length=389133
time=2024-07-11T18:38:09.217Z level=INFO msg="200: OK" request.time=2024-07-11T18:38:09.216Z request.method=GET request.host=localhost:8080 request.path=/assets/react-dom-BOasIFCf.js request.query="" request.ip=172.17.0.1:47886 request.referer="http://localhost:8080/jobs?state=running" request.length=0 response.time=2024-07-11T18:38:09.217Z response.latency=540.133µs response.status=200 response.length=141201
time=2024-07-11T18:38:09.217Z level=INFO msg="200: OK" request.time=2024-07-11T18:38:09.217Z request.method=GET request.host=localhost:8080 request.path=/assets/reactflow-BySh6Uv9.js request.query="" request.ip=172.17.0.1:47878 request.referer="http://localhost:8080/jobs?state=running" request.length=0 response.time=2024-07-11T18:38:09.217Z response.latency=393.285µs response.status=200 response.length=142956
time=2024-07-11T18:38:09.218Z level=INFO msg="200: OK" request.time=2024-07-11T18:38:09.218Z request.method=GET request.host=localhost:8080 request.path=/assets/index-4_DTMP3B.css request.query="" request.ip=172.17.0.1:47874 request.referer="http://localhost:8080/jobs?state=running" request.length=0 response.time=2024-07-11T18:38:09.218Z response.latency=274.089µs response.status=200 response.length=90079
time=2024-07-11T18:38:09.337Z level=ERROR msg="error running API route" error="error getting states and counts: failed to connect to `user=postgres database=main`:\n\t127.0.0.1:5433 (localhost): dial error: dial tcp 127.0.0.1:5433: connect: connection refused\n\t[::1]:5433 (localhost): dial error: dial tcp [::1]:5433: connect: connection refused"
time=2024-07-11T18:38:09.337Z level=INFO msg="500: Internal Server Error" request.time=2024-07-11T18:38:09.334Z request.method=GET request.host=localhost:8080 request.path=/api/states request.query="" request.ip=172.17.0.1:47878 request.referer="http://localhost:8080/jobs?state=running" request.length=0 response.time=2024-07-11T18:38:09.337Z response.latency=3.004733ms response.status=500 response.length=69
time=2024-07-11T18:38:09.338Z level=ERROR msg="error running API route" error="error beginning transaction: failed to connect to `user=postgres database=main`:\n\t127.0.0.1:5433 (localhost): dial error: dial tcp 127.0.0.1:5433: connect: connection refused\n\t[::1]:5433 (localhost): dial error: dial tcp [::1]:5433: connect: connection refused"
time=2024-07-11T18:38:09.338Z level=INFO msg="500: Internal Server Error" request.time=2024-07-11T18:38:09.334Z request.method=GET request.host=localhost:8080 request.path=/api/jobs request.query="state=running&limit=20" request.ip=172.17.0.1:47874 request.referer="http://localhost:8080/jobs?state=running" request.length=0 response.time=2024-07-11T18:38:09.338Z response.latency=3.777557ms response.status=500 response.length=69
time=2024-07-11T18:38:09.356Z level=INFO msg="200: OK" request.time=2024-07-11T18:38:09.356Z request.method=GET request.host=localhost:8080 request.path=/icon.svg request.query="" request.ip=172.17.0.1:47878 request.referer="http://localhost:8080/jobs?state=running" request.length=0 response.time=2024-07-11T18:38:09.356Z response.latency=36.559µs response.status=200 response.length=1848
time=2024-07-11T18:38:09.356Z level=INFO msg="200: OK" request.time=2024-07-11T18:38:09.356Z request.method=GET request.host=localhost:8080 request.path=/apple-icon.png request.query="" request.ip=172.17.0.1:47874 request.referer="http://localhost:8080/jobs?state=running" request.length=0 response.time=2024-07-11T18:38:09.356Z response.latency=162.588µs response.status=200 response.length=5532
time=2024-07-11T18:38:09.840Z level=INFO msg="200: OK" request.time=2024-07-11T18:38:09.839Z request.method=GET request.host=localhost:8080 request.path=/assets/Inter-Bold-CuhepTt8.woff2 request.query="v=3.19" request.ip=172.17.0.1:47874 request.referer=http://localhost:8080/assets/index-4_DTMP3B.css request.length=0 response.time=2024-07-11T18:38:09.840Z response.latency=220.829µs response.status=200 response.length=106140
```
I suspect it doesn't like the DSN connection string.

### PR DESCRIPTION
**Pull request by brandur**
Reveal a Postgres connect error as user-facing. This will be helpful for
operators in debugging a River UI installation, especially when first
setting it up.

We use the full error string from the Pgx connect error -- it contains
useful context and Pgx is smart enough to already sanitize it such that
it won't contain a password or other secrets.

Fixes #93.

### CODE REVIEW

**Comment by bgentry** [comment]
> We use the full error string from the Pgx connect error -- it contains useful context and Pgx is smart enough to already sanitize it such that it won't contain a password or other secrets.

Are you certain about this? In the run up to releasing this, I took steps to make sure we did not return the raw errors via the API specifically because I did see one that included connection details. I’m not positive that creds were in there, but I feel like they were and that’s what jolted me into making the previous change.

Maybe instead of directly returning the backend error we can detect it and expose something more generic about the database connection not working and tell users to check the logs? (Which we can probably tidy up and make more prominent in this situation)

**Comment by brandur** [comment]
> Maybe instead of directly returning the backend error we can detect it and expose something more generic about the database connection not working and tell users to check the logs? (Which we can probably tidy up and make more prominent in this situation)

Hmm, could do, but I'm 100% sure that creds are redacted. By reading Pgx's source code, it looks fairly clear to me that Jack took measures to explicitly not mention a password:

```go
// ConnectError is the error returned when a connection attempt fails.
type ConnectError struct {
	Config *Config // The configuration that was used in the connection attempt.
	err    error
}

func (e *ConnectError) Error() string {
	prefix := fmt.Sprintf("failed to connect to `user=%s database=%s`:", e.Config.User, e.Config.Database)
	details := e.err.Error()
	if strings.Contains(details, "\n") {
		return prefix + "\n\t" + strings.ReplaceAll(details, "\n", "\n\t")
	} else {
		return prefix + " " + details
	}
}
```

**Comment by bgentry** [comment]
Maybe I saw the url and user and it still scared me enough, especially given the DB may be externally accessible and not locked into a vpc or IP restricted. I guess that’s only a major issue in public deployments like the demo app 🤔

**Comment by brandur** [comment]
Alright, updated to show a fairly generic connection error with a note to check logs.

**Pull request merged**
